[package]
name = "fp-storage"
version = "2.0.0"
authors = ["AXIA Technologies <admin@axiacoin.network"]
edition = "2018"
description = "Storage primitives for Ethereum RPC (web3) compatibility layer for Axlib."
license = "Apache-2.0"

[features]
default = ["std"]
std = []
